apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-analytics
  labels:
    app: basic_model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic_model
  template:
    metadata:
      labels:
        app: basic_model
    spec:
      containers:
        - name: serve
          image: rstana/api_serve:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: basic_model
  ports:
    - protocol: TCP
      port: 32050
      targetPort: 5000
